import Service from '@/components/Service';
import React from 'react'


export const metadata = {
    title: "Our Services",
    description: "Generated by create next app",
  };

const page = () => {
  return (
    <div>
      <h1>below are our services</h1>

      <div className='flex flex-wrap gap-2 justify-around py-10'>
      <Service no={1} />
      <Service no={2} />
      <Service no={3} />
      <Service no={4} />
      <Service no={5} />
      <Service no={6} />
      <Service no={7} />
      <Service no={8} />
       
        
      </div>
    </div>
  )
}

export default page
