import React from 'react'



export const metadata = {
  title: "New pagesss",
  description: "Generated by Next Js",
};


const page = () => {
  return (
    <div>
      i am afeature outlinediv
      <div>helloi</div>
    </div>
  )
}

export default page
